0.3.1

diff --git a/bin/sparky-aptus-upgrade b/bin/sparky-aptus-upgrade
--- a/bin/sparky-aptus-upgrade
+++ b/bin/sparky-aptus-upgrade
@@ -3,7 +3,7 @@
 # Sparky APTus Upgrade is a simply tool for upgrading the system
 # Created by Paweł "pavroo" Pijanowski 2014/10/31
 # Copyright 2014-2018 under the GNU GPL2 License
-# Last update 2018/03/17
+# Last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus-upgrade"
@@ -46,10 +46,11 @@ ENTRYTEXT="--entry-text"
 MSGBOX=" --button=Ok:0"
 NOBUTTONS="--no-buttons"
 
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 if [ -f /usr/bin/sparky-editor ]; then
@@ -73,7 +74,7 @@ if [ "$PINGTEST" = "" ]; then
     exit 1
 fi
 
-$SPARKYXTERM -e "apt-get update"
+$SPARKYXTERM "apt-get update"
 sleep 1
 
 # preper temporary folder
@@ -138,19 +139,21 @@ eval exec $cmd
 else
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL8"
 	exit 0
-
 fi
 }
 
 upgrademenu () {
-$SPARKYXTERM -e "apt full-upgrade --no-install-recommends -y --force-yes && apt install -f"
+$SPARKYXTERM "apt full-upgrade --no-install-recommends -y --force-yes"
+$SPARKYXTERM "apt install -f"
 sleep 1
+
 # re-check is your system up-to-date
 mainmenu
 }
 
 changelogmenu () {
 $SPARKYEDITOR /tmp/aptus-upgrade/changelog
+
 dialogmenu
 }
 
